### ISSUE TITLE
Support Connectorg

### ISSUE THREAD

**Issue by OneWorldStudio** [magistr-of-code/fancy-vfx#3]
Hello, please add Connector support

[crash-2024-11-22_15.49.26-fml.txt](https://github.com/user-attachments/files/17878915/crash-2024-11-22_15.49.26-fml.txt)

**Comment by magistr-of-code** [comment]
Hello. Based on your error i can suggest installing porting lib.

**Comment by OneWorldStudio** [comment]
![Uploading image.png…]()


> Здравствуйте. Исходя из вашей ошибки я могу предложить установить porting lib.

**Comment by OneWorldStudio** [comment]
![image](https://github.com/user-attachments/assets/85a1fd6c-734b-4d47-965a-52149eb0f128)

**Comment by OneWorldStudio** [comment]
> Hello. Based on your error i can suggest installing porting lib.

![image](https://github.com/user-attachments/assets/abf63240-c414-4c62-931d-b61ecc97efd5)

**Comment by magistr-of-code** [comment]
Then there is not much i can do about it since my mod is heavenly dependent on that library.
