### ISSUE TITLE
Incompatible with Embeddium or Iris

### ISSUE THREAD

**Issue by Prime54601** [magistr-of-code/fancy-vfx#5]
Game crashes with Fancy VFX, Embeddium and Iris installed. Removing Embeddium and Iris makes it load properly.

**Comment by Prime54601** [comment]
I'm on 1.20.1 and Adoptium JAVA 22 btw

**Comment by magistr-of-code** [comment]
Mod should be fully compatible with iris. But i am unsure if it is compatible with Embeddium. Can i see your logs please?

**Comment by Prime54601** [comment]
> Mod should be fully compatible with iris. But i am unsure if it is compatible with Embeddium. Can i see your logs please?

Sorry for the late reply. I made the log with a bunch of mods but it's the same with just embeddium and iris.

[latest.log](https://github.com/user-attachments/files/18536303/latest.log)
